add version bump script
obsidianmd/obsidian-sample-plugin pull request #10
Opened 2021-06-05 13:42 UTC by AidenLx

Use `npm version` to bump version in `package.json`, `manifest.json` and `version.json`
- `.npmrc` is used to remove the prefix of git tags (`1.0.0` in favor of `v1.0.0`)
- version number in `version.json` is fetched from `minAppVersion` of `manifest.json`

2022-01-21 13:58 UTC, Edo78 commented
just a couple of questions:

1. is it possibile to relase such feature specifing that it works only on posix system?
2. I don't have a non posix system so I have no idea about what "unexpected effects" this PR could have. Can you be more specific so that someone can try to solve them?

2022-01-21 17:01 UTC, JeppeKlitgaard commented
The command simply fails, I believe. I can't recall if it leaves the respective files in a dirty state, but with Git set up anyway this shouldn't be too harmful.

I think a better option would be to add a JS-based tool to the Obsidian npm package that could do this.

2022-01-22 09:51 UTC, aidenlx commented
@JeppeKlitgaard now I've updated to use a simple node script instead of shell script so it should break in non-POSIX environment

for advanced devs they can use solution like [release-it](https://github.com/release-it/release-it) or GitHub Action to do version bump

2022-01-22 12:39 UTC, Edo78 commented
@aidenlx just wondering why you changed from 4 to 2 spaces (even if I prefer this way I think it's outside the scope of this PR and it made harder to find differences)

2022-01-22 16:41 UTC, lishid requested changes

2022-01-22 16:41 UTC, lishid commented on version-bump.mjs
> +let menifest = JSON.parse(readFileSync("manifest.json").toString());
I think using `readFileSync(path, 'utf8')` makes it a string output directly.

2022-01-22 16:41 UTC, lishid commented on version-bump.mjs
> +let menifest = JSON.parse(readFileSync("manifest.json").toString());
Also typo here with `manifest`.

2022-01-22 16:41 UTC, lishid commented on version-bump.mjs
> +let versions = JSON.parse(readFileSync("versions.json").toString());
Same as above.

2022-01-22 16:41 UTC, lishid commented on README.md
> +> You can simplify the version bump process by running `npm version patch`, `npm version minor` or `npm version major` after updating minimum-obsidian-version manually in `manifest.json`.
minimum-obsidian-version => minAppVersion

2022-01-22 17:32 UTC, Edo78 commented on version-bump.mjs
> +let menifest = JSON.parse(readFileSync("manifest.json").toString());
I'm just a passerby but `const` is usually preferable than `let` and you can still modify the properties.
Eg.
```
const obj = {'a':'b'};
obj.a = 'c';
```

2022-01-22 17:36 UTC, Edo78 commented on version-bump.mjs
> +versions[targetVersion] = minAppVersion;
Hi, it's me again. Just pointing out that al L8 you wrote `menifest.version` and now `versions[targetVersion]`.
What the preferred style to access to a property?

2022-01-22 17:37 UTC, lishid commented on version-bump.mjs
> +versions[targetVersion] = minAppVersion;
`targetVersion` is a variable 😉

2022-01-22 17:42 UTC, Edo78 commented on version-bump.mjs
> +versions[targetVersion] = minAppVersion;
LOL sorry

2022-01-22 20:13 UTC, aidenlx commented
Done in [976798](https://github.com/obsidianmd/obsidian-sample-plugin/pull/10/commits/976798a086528d26a8363680d431f48708db7154)

2022-01-22 21:13 UTC, merged

2022-01-22 21:14 UTC, lishid commented
Thank you!